# Generated by Django 5.0.6 on 2024-07-15 10:17

import apps.animals_crm.models.animal_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_crm', '0004_animalcard_description_animalcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalphoto',
            name='image',
            field=models.ImageField(default='photos/default.jpg', upload_to=apps.animals_crm.models.animal_photo.get_animal_avatar_path),
        ),
    ]
