version: "3.8"

services:
  app:
    ports:
      - "60000:8000"
    command: /start.sh

    volumes: &app_volumes
      - ./files:/wd/files:rw # TODO: Remove this after migration to media.
      - ./media:/wd/media:rw
      - ./staticfiles:/wd/staticfiles:rw
    user: "${UID:-1000}"
    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  init:
    volumes: *app_volumes
    user: "${UID:-1000}"
    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  postgres:
    ports:
      - "55432:5432"

  pgadmin:
    image: dpage/pgadmin4:8.7
    ports:
      - "55050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-admin@mail.com}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-admin123}"

    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - admin_tools
