version: "3.8"

volumes:
  postgres_data: {}

networks:
  internal: {}
  public: {}

x-app: &app
  build: .

services:
  app:
    <<: *app
    depends_on:
      init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    profiles:
      - full_dev

    networks:
      - internal
      - public

  init:
    <<: *app
    depends_on:
      postgres:
        condition: service_healthy
    command: /init.sh

    profiles:
      - full_dev
      - local_dev

    networks:
      - internal

  postgres:
    image: postgres:16.3-alpine3.20

    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username ${POSTGRES_USER} --dbname ${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

    profiles:
      - full_dev
      - local_dev

    networks:
      - internal

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    profiles:
      - full_dev
      - local_dev

    networks:
      - internal

  celery:
    <<: *app
    command: celery -A myproject worker --loglevel=info
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

    profiles:
      - full_dev
      - local_dev

    networks:
      - internal
