version: "3.8"

#volumes:
#      postgres_data: {}
#      app_media: {}
#      app_staticfiles: {}

services:
  app:
    ports:
      - "60000:8000"
    command: /start.sh

    volumes: &app_volumes
      - ./files:/wd/files:rw
      - ./media:/wd/media:rw
      - ./staticfiles:/wd/staticfiles:rw

    user: "${UID:-1000}"
    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      DJANGO__CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672/"

  init:
    volumes: *app_volumes
    user: "${UID:-1000}"
    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  postgres:
    ports:
      - "55432:5432"

  rabbitmq:
    ports:
      - "5672:5672"

  celery-worker:
    volumes: *app_volumes

    user: "${UID:-1000}"
    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      DJANGO__CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672/"
